version: '3.7'

volumes:
  node_modules:
  cypress_binary:

services:
  app:
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=dev
    restart: always
    ports:
      - "9191:8080"
    volumes:
      - ./:/home/node/app/
      - /home/node/.npm
      - node_modules:/home/node/app/node_modules
      - cypress_binary:/root/.cache/Cypress

  test_e2e:
    image: cypress/base:10
    working_dir: /app
    environment:
      CYPRESS_baseUrl: http://app:9191/
      VUE_APP_BACK_END_API: http://app/api/
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - cypress_binary:/root/.cache/Cypress
    command: "node_modules/cypress/bin/cypress run"
    depends_on:
      - app
