enum GameStoreGetters {
  GET_ACTIVE_USER = 'GET_ACTIVE_USER',
  GET_TERM_MOVIES = 'GET_TERM_MOVIES',
  GET_ACTIVE_TERM = 'GET_ACTIVE_TERM',
  GET_MOVIE_GUESSINGS = 'GET_MOVIE_GUESSINGS',
  GET_ACTIVE_GAME = 'GET_ACTIVE_GAME',
}

export default GameStoreGetters;
